config/routes.rb
Rails.application.routes.draw do

  get 'blogs/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { registrations: 'registrations', sessions: 'sessions' }
  root 'home#index'

  get 'users/edit_profile', to: 'users#edit_profile', as: :user_edit_profile
  get 'users/show/profile', to: 'users#show_profile', as: :user_profile
  put 'add_to_wish_list', to: 'users#add_to_wish_list', as: :add_to_wish_list
  get 'user/dashboard', to: 'users#user_dashboard', as: :user_dashboard
  get 'user/new_address', to: 'users#new_address', as: :new_address
  get 'user/address_book', to: 'users#address_book', as: :address_book
  get 'student_club', to: 'users#student_club', as: :student_club
  get 'user_lists', to: 'users#user_lists', as: :user_lists
  post 'user/lists', to: 'users#create_list', as: :create_list
  get 'user/:id/lists', to: 'users#edit_list', as: :edit_list
  delete 'remove/list/product/:id', to: 'users#remove_from_list', as: :remove_from_list
  get 'my/orders', to: 'users#show_orders', as: :show_orders
  get 'order/:id', to: 'users#order_details', as: :order_details
  post 'user/new/address', to: 'users#add_new_address', as: :add_new_address
  get 'edit/:id/address', to: 'users#edit_address', as: :edit_address
  patch 'edit/:id/address', to: 'users#update_address', as: :update_address
  delete 'remove/address/:id', to: 'users#destroy_address', as: :destroy_address
  put '/set/default_address', to: 'users#set_default_address'
  get 'edit/:id/student_profile', to: 'users#edit_student_club', as: :edit_student_club
  put 'edit/:id/student_profile', to: 'users#update_student_club', as: :update_student_club
  get 'reviews', to: 'users#show_reviews', as: :reviews
  
  resources :products , only:[:index, :show]
  resources :blogs, only:[:index, :show]

  get 'terms_and_conditions', to: "requests#terms_and_conditions"
  get 'privacy_policy', to: "requests#privacy_policy"
  get "new_book_request", to: "requests#book_request_new"
  post 'book_requests', to: "requests#book_request_create"
  get "study_abroad", to: "requests#study_abroad_new"
  post 'study_abroads', to: "requests#study_abroad_create"
  get 'publish_request', to: 'requests#publish_requests_new'
  post 'publish_requests', to: 'requests#publish_requests_create'
  get 'bulk_order_info', to: 'requests#bulk_order_info'
  get 'new/student/membership', to: 'requests#new_student_membership_request', as: :new_student_membership
  post 'student/membership/step/one', to: 'requests#student_membership_step_one_create', as: :student_membership_step_one
  put 'student/membership/update', to: 'requests#student_membership_update', as: :student_membership_update
  get 'advertise', to: 'requests#advertise'
  post 'advertise_enquiry_create', to: 'requests#advertise_enquiry_create'

  resources :requests, :path => '', only:[:none] do 
    collection do
      get 'aboutus', to: 'faqs/aboutus_faqs'
      get 'bulk_order_faqs', to: 'faqs/bulkOrder_faqs'
      get 'publish_faqs', to: 'faqs/publish_faqs'
      get 'student_membership_faqs', to: 'faqs/student_membership_faqs'
      get 'forget_password_faqs', to: 'faqs/forget_password_faqs'
      get 'publisher_author_guidelines_faqs', to: 'faqs/publisher_author_guidelines_faqs'
      get 'shipping_delivary_faqs', to: 'faqs/shipping_delivary_faqs'
      get 'request_book_faqs', to: 'faqs/request_book_faqs'
      get 'shipping_rates_faqs', to: 'faqs/shipping_rates_faqs'
      get 'careers', to: 'requests#careers'
      get 'contact_us', to: 'requests#contact_us'
      post 'contact_us', to: 'requests#create_new_contact_request'
      get 'bulk_order_discounts', to: 'requests#bulk_order_discounts'
      post 'create_bulk_order_discount', to: 'requests#create_bulk_order_discount'
    end
  end

  resources :carts, only:[:none] do
    member do 
      put 'add_to_cart'
      put 'increase_quantity'
      put 'decrease_quantity'
      put 'decrease_quantity_cart'
      put 'increase_quantity_cart'
    end

    collection do 
      get 'show', as: :cart
    end 
  end

  resources :orders, only: [:create]
  get 'check_out', to: 'orders#check_out', as: :check_out

  resources :reviews, only:[:update, :destroy, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  enum user_type: [:simple, :student]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :addresses, dependent: :destroy
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_one :student_profile, dependent: :destroy
  has_many :wish_lists, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :email, 
	      # you only need presence on create
	      :presence => { :on => :create },
	      # and use confirmation to ensure they always match
	      :confirmation => true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_product, only:[:add_to_wish_list]
  before_filter :authenticate_user!



# ===============User Profile===============
	def show_profile
		@profile = current_user.student_profile if current_user.student_profile.present?
  	@user = current_user
	end

  def edit_profile
  	@profile = current_user.student_profile
  	@user = current_user
  end
# ===============User Profile=================


# ===============User orders==================
def show_orders
  if params[:page] == 'all'
    @orders = current_user.orders
  else
    @orders = current_user.orders.page((params[:page] || 1)).per(2)
  end 
end

def order_details
  @order = Order.find params[:id]
  @counts = @order.products.group(:id).count
end
# ===============User orders==================

# ===========User wishlist====================
  def user_lists
    @lists = current_user.wish_lists if current_user.wish_lists.present?  
  end

  def create_list
    @list = current_user.wish_lists.create(name: params[:wish_list][:name])
    if @list.save
      flash[:info] = 'List created successfully!'
      redirect_to :back
    else
      flash[:alert] = 'Please enter name for list!'
      redirect_to :back
    end
  end

  def edit_list
    @list = current_user.wish_lists.where(id: params[:id]).first
  end

  def remove_from_list
    @list = current_user.wish_lists.where(id: params[:list]).first
    @list.products.delete(Product.find(params[:id]))
    if @list.save
      flash[:info] = 'Book has been deleted from your wishlist!'
      redirect_to :back
    else
      flash[:alert] = 'Something went wrong!'
      redirect_to :back
    end
  end

  def add_to_wish_list
  	if params[:wish_list][:list_ids].present?
      params[:wish_list][:list_ids].each do |id|
        list = WishList.find id
        list.products << @product if !list.products.where(id: @product.id).present?  
        list.save
      end
      return flash.now[:info] = 'Book has been added to your wishlist!'
  	else
  		return flash.now[:alert] = 'Please select any list!'
  	end
  end
# ===========User wishlist====================

  def user_dashboard
    @user = current_user
  end

  # ===============user addressbook===============
  def address_book
    @addresses = current_user.addresses
  end

  def new_address
    @address = Address.new
    respond_to do |format|
      format.js {render layout: false} 
    end
  end

  def add_new_address
    @address = Address.create(address_params)
    current_user.addresses << @address
    flash[:info] = "New address added successfully!"
  end

  def edit_address
    @address = Address.find params[:id]
    respond_to do |format|
      format.js {render layout: false} 
    end
  end

  def update_address
    @address = Address.find params[:id]
    @address.update(address_update_params)
    flash[:info] = "Address updated successfully!"
    if @address.save
      redirect_to request.referer  
    end
  end

  def destroy_address
    @address = Address.find params[:id]
    @address.destroy
    flash[:info] = "Address removed successfully!"
    respond_to do |format|
      format.js {redirect_to request.referer} 
    end
  end

  def set_default_address
    @address = current_user.addresses.where(id: params[:id]).first
    @previous_addr = current_user.addresses.where(default_address: true).first
    @previous_addr.default_address = false if @previous_addr.present?
    @address.default_address = true
    @address.save
    @previous_addr.save if @previous_addr.present?
    flash[:info] = "Address updated successfully!"
    respond_to do |format|
      format.js {redirect_to :back
      }
    end
  end
  # ===============user addressbook===============



  # ===============student club===================

  def student_club
    @profile = current_user.student_profile if current_user.student_profile.present?
  end

  def edit_student_club
    @profile = current_user.student_profile 
  end

  # ===============student club===================


  # ===============reviews===================
  def show_reviews
    @reviews = current_user.reviews
  end

  # ===============reviews===================
  private

  def set_product
  	@product = Product.find params[:wish_list][:product_id]
  end

  def address_params
    params.require(:address).permit(:first_name, :last_name, :title, :postal_address, :city, :state, :country)
  end

  def address_update_params
    params.require(:address).permit(:first_name, :last_name, :title, :postal_address, :city, :state, :country)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_sidebar_menu.html.erb
<div class="col-md-3 col-sm-4 col-xs-12">
	<div class="userDashboard-list">
	  <ul class="nav nav-tabs" id="menu" role="tablist">
	    <li role="presentation" class="show_profile edit_profile dashboard-profile">
	    	<a href="<%= user_profile_path %>" role="tab" >
	    		<span>text</span>
	    		My Profile
	    	</a>
	    </li>
	    <li role="presentation" class="show_orders dashboard-order order_details">
	    	<a href="<%= show_orders_path %>" role="tab">
	    		<span>text</span>
	    		Orders
	    	</a>
	    </li>
	    <li role="presentation" class="dashboard-list user_lists edit_list">
	    	<a href="<%= user_lists_path %>" role="tab">
		    	<span>text</span>
		    	Lists
	    	</a>
	    </li>
	    <li role="presentation" class="dashboard-payment">
	    	<a href="#payment" aria-controls="payment" role="tab" data-toggle="tab">
	    		<span>text</span>
	    		Payment
	    	</a>
	    </li>
	    <li role="presentation" class="dashboard-address address_book">
	    	<a href="<%= address_book_path %>"  role="tab" >
	    		<span>text</span>
	    		Addresses
	    	</a>
	    </li>
	    <li role="presentation" class="dashboard-review show_reviews">
	    	<a href="<%= reviews_path %>" role="tab">
	    		<span>text</span>
	    		Reviews
	    	</a>
	    </li>
	    <li role="presentation" class="dashboard-club">
	    	<a href="<%= student_club_path %>" aria-controls="studentclub">
	    		<span>text</span>
	    		Droppingo Student Club
	    	</a>
	    </li>
	  </ul>
	</div>
</div>

app/views/users/address_book.html.erb
<div class="main-content user-dashboard">
	<!-- /.banner-after-content -->
	<div class="banner-after-content">
		<div class="container">
			<div class="row">
				<%= render partial: "sidebar_menu" %>
				<div class="col-md-9 col-sm-8 col-xs-12">
					<div class="bac-right userDashboard-content">
						<div class="tab-content">
							<div class="address-block">
								<div class="bac-heading">
									<h1>Addresses</h1>
									<h4>Manage Address Book</h4>
								</div>
								<div class="udc-detail add-new-address">
									<div class="row">
										<% if @addresses.present? %>
											<% @addresses.each do |address| %>
												<div class="col-md-4 col-sm-6 col-xs-12">
													<div class="newAdd-content">
														<div class="nac-address">
															<p><%= address.title %>. <%= address.first_name %> <%= address.last_name %></p>
															<p class="nac-address-p"><%= address.postal_address %></p>
															<p><%= address.city%></p>
															<p><%= address.state %></p>
															<p><%= address.country %></p>
															<div class="nac-address-btn">
																<%= link_to 'Edit', edit_address_path(address), remote: true, class: "edit-btn blue-btn user-dashboard-btn"%>
																<%= link_to 'Delete', destroy_address_path(address), method: :delete, remote: true, class: "edit-btn blue-btn user-dashboard-btn"%>
															</div>
														</div>
														<div class="nac-checkbox">
															<% if address.default_address %> 
																<input type="radio" name="default_address" class="css-checkbox" checked="true"/>
															<% else %>
																<input type="radio" name="default_address" class="css-checkbox"/>
															<% end %>
															<label for="radio5" id="<%=address.id%>" class="css-label radGroup2">Default delivery address</label>
														</div>
													</div>
												</div>
											<% end %>
										<% else %>
											<div class="col-md-12">
												<p class="udc-para">You do not have any addresses stored in your book. Please click on the "Add a New Address" button to update your address book.</p>
											</div>
										<% end %>
										<div class="col-md-4 col-sm-6 col-xs-12">
											<div class="newAdd-content addnewAdd-content">
												<a href="<%= new_address_path %>" data-remote="true">
													<span class="add-newAdd-span">+ Add a new address</span>
												</a>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="form"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	$( ".add-newAdd-span" ).click(function() {
		$('.address-block').hide();
		$('.form').show();
	});
	$( ".edit-btn" ).click(function() {
		$('.address-block').hide();
		$('.form').show();
	});
	$(".css-label").click(function(){
		var addr_id = $(this).attr("id");
		  $.ajax({
	    type:'PUT', 
	    url: '/set/default_address', 
	    data: $.param({ id: addr_id})
		});
	});
</script>

<script type="text/javascript">
	$(document).ready(function(){
    $('li').removeClass('active');
    $(".<%= params[:action] %>").addClass("active");
	});
</script>

app/views/users/edit_address.js.erb
$(".form").html("<%= escape_javascript(render partial: 'form', locals: { address: @address }) %>");

app/views/users/show_orders.html.erb
<div class="main-content user-dashboard">
	<!-- /.banner-after-content -->
	<div class="banner-after-content">
		<div class="container">
			<div class="row">
				<%= render partial: "sidebar_menu" %>
				<div class="col-md-9 col-sm-8 col-xs-12">
					<div class="bac-right userDashboard-content">
						<div class="tab-content">
							<div class="bac-heading">
								<h1>MY ORDERS</h1>
								<h4>Recent Orders</h4>
							</div>
							<div class="edit-orders-form"></div>
							<div class="udc-detail dashboard-order-detail">
								<div class="table-responsive">
									<table class="table table-striped orders-table">
										<thead>
											<tr>
												<th>Order No.</th>
												<th>Order Date</th>
												<th>Status</th>
												<th>Date Shipped</th>
												<th>Details</th>
											</tr>
										</thead>
										<tbody>
											<% @orders.each do |order| %>
												<tr>
													<td><%= order.id %></td>
													<td><%= order.created_at.strftime("%Y-%m-%d") %></td>
													<td><%= order.status %></td>
													<td><%= order.shipping_date.strftime("%Y-%m-%d") if order.shipping_date.present? %></td>
													<td><a href="<%= order_details_path(order) %>" class="d-newlist-btn">View Order</a></td>
												</tr>
											<% end %>
										</tbody>
									</table>
								</div>
								<% if @orders.count == current_user.orders.count %>
									<a href="<%= show_orders_path(page: 'less') %>" class="d-newlist-btn view-all-btn">View Less</a>
								<% else %>
									<a href="<%= show_orders_path(page: 'all') %>" class="d-newlist-btn view-all-btn">View All</a>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	// $( ".edit-profile-btn" ).click(function() {
	// 	$('.view-profile-block').hide();
	// 	$('.edit-profile-form').show();
	// });
	$(document).ready(function(){
    $('li').removeClass('active');
    $(".<%= params[:action] %>").addClass("active");
	});
</script>

app/views/users/student_club.html.erb
<div class="main-content user-dashboard">
	<!-- /.banner-after-content -->
	<div class="banner-after-content">
		<div class="container">
			<div class="row">
				<%= render partial: "sidebar_menu" %>
				<div class="col-md-9 col-sm-8 col-xs-12">
					<div class="bac-right userDashboard-content">
						<div class="tab-content">
							<div class="bac-heading">
									<h1>DROPPINGO STUDENT CLUB <span class="dashboard-beta">Beta</span></h1>
								</div>
								<div class="udc-detail">
									<div class="student-club-block">
										<% if @profile.present? %>
											<%= form_tag do %>
												<p>
													<%= label_tag "Instituition Name: " %>
													<%= label_tag @profile.institution_name %>
												</p>
												<p>
													<%= label_tag "Current Educational Level: " %>
													<%= label_tag @profile.current_educational_level %>
												</p>
												<p>
													<%= label_tag "Current Area of study: " %>
													<%= label_tag @profile.area_of_study %>
												</p>
												<p>
													<%= label_tag "Year of study: " %>
													<%= label_tag @profile.year_of_study %>
												</p>
												<p>
													<%= label_tag "Course Length: " %>
													<%= label_tag @profile.course_length %>
												</p>
												<p>
													<%= label_tag 'Gender: ' %>
													<%= label_tag @profile.gender %>
												</p>
												<p>
													<%= label_tag 'Mobile #: ' %>
													<%= label_tag @profile.mobile_no %>
												</p>
												<p>
													<%= label_tag 'Date of Birth: ' %>
													<%= label_tag @profile.date_of_birth %>
												</p>
											<% end %>
											<%= link_to 'Edit Student Profile', edit_student_club_path(@profile.id), class: 'edit-student-club blue-btn user-dashboard-btn', remote: true %>
										</div>
										<div class="student-club-edit-form"></div>
									<% else %>
								<!-- </div> -->
										<p class="udc-para">Droppingo Student Club is Pakistan’s Largest Student Platform for verified students and give students exclusive access to discounts, deals and offers, along with opportunities to intern, work and other cool stuff!</p>
										<p class="udc-para">If you’re a student and already a Droppingo Member you can fill out the form below to become a Student Club member to enjoy exclusive access to awesome student stuff.</p>
										<div class="db-form-container">
											<%= form_for :student_profile, remote: true, method: :post, html: {class: "form-inline studentMember-form dashboard-form"}, :url => student_membership_step_one_path do |f| %>
												<%= f.hidden_field :name, value: current_user.first_name+ " " +current_user.last_name %>
												<%= f.hidden_field :email, value: current_user.email %>
												<div class="form-group">
													<label>NAME OF INSTITUTION</label>
													<%= f.text_field :institution_name, class: "form-control sm-form-fields" %>
												</div>
												<div class="form-group">
													<label>CURRENT EDUCATION LEVEL</label>
													<%= f.select :current_educational_level, options_for_select([["Select Current Education Level", ""], "Bachelors Degree", "Masters", "PhD", "Others"]), :class => 'form-control sm-form-fields' %>
												</div>
												<div class="form-group">
													<label>COURSE / AREA OF STUDY</label>
													<%= f.text_field :area_of_study, class: "form-control sm-form-fields" %>
												</div>
												<div class="form-group">
													<label>YEAR OF STUDY</label>
													<%= f.select :year_of_study, options_for_select([["Year of study", ""], "Freshmen", "Sophomor", "Junior", "Senior"]),  :class => 'form-control sm-form-fields' %>
												</div>
												<div class="form-group">
													<label>COURSE LENGTH</label>
													<%= f.select :course_length, options_for_select([["Length of course"], "1", "2", "3", "4"]), :class => 'form-control sm-form-fields' %>
												</div>
												<div class="form-group">
													<label>STUDENT ID / ROLL NO.</label>
													<%= f.text_field :student_id, class: "form-control sm-form-fields" %>
												</div>
												<div class="form-group">
													<label class="">MOBILE NO.</label>
													<%= f.text_field :mobile_no, class: "form-control sm-form-fields" %>
												</div>
												<div class="form-group">
													<div class="row studentClub-birthday-set">
														<div class="col-md-4">
															<label>Date of Birth</label>
														</div>
														<div class="col-md-8">
															<div class="form-group sm-birthday-set">
																<%= f.date_select(:date_of_birth, :order => [:month, :day, :year], :start_year=>1970, :end_year=>2010, :class => "form-control sm-form-fields", placeholder: "Birth Date")%>
															</div>
														</div>
													</div>
												</div>
												<div class="form-grou text-right">
													<%= f.hidden_field :redirect, value: true %>
													<%= f.submit 'SUBMIT', :class => 'blue-btn user-dashboard-btn' %>
												</div>
											<%end%>
										</div>
									<% end %>
					    	</div>
					    </div>
					  </div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	$( ".edit-student-club" ).click(function() {
		$('.student-club-block').hide();
		$('.student-club-edit-form').show();
	});
</script>

app/views/users/user_dashboard.html.erb
<div class="main-content user-dashboard">
	<!-- /.banner-after-content -->
	<div class="banner-after-content">
		<div class="container">
			<div class="row">
				<%= render partial: "sidebar_menu" %>
				<div class="col-md-9 col-sm-8 col-xs-12">
					<div class="bac-right userDashboard-content">
						<div class="tab-content">
					    <div role="tabpanel" class="tab-pane profile-tab" id="profile"></div>
					    <div role="tabpanel" class="tab-pane order-tab" id="order">...</div>
					    <div role="tabpanel" class="tab-pane payment-tab" id="payment">...</div>
					    <div role="tabpanel" class="tab-pane address-tab" id="address">
					    	<!-- <div class="address-block">
					    		<div class="bac-heading">
										<h1>Addresses</h1>
										<h4>Manage Address Book</h4>
									</div>
									<div class="udc-detail add-new-address">
										<p class="udc-para">You do not have any addresses stored in your book. Please click on the "Add a New Address" button to update your address book.</p>
										<div class="row">
											<% if @addresses.present? %>
												<% @addresses.each do |address| %>
													<div class="col-md-4 col-sm-6 col-xs-12">
														<div class="newAdd-content">
															<div class="nac-address">
																<p><%= address.title %>. <%= address.first_name %> <%= address.last_name %></p>
																<p><%= address.postal_address %></p>
																<p><%= address.city%></p>
																<p><%= address.state %></p>
																<p><%= address.country %></p>
																<div class="nac-address-btn">
																	<%= link_to 'Edit', edit_address_path(address), remote: true, class: "edit-btn blue-btn user-dashboard-btn"%>
																	<%= link_to 'Delete', destroy_address_path(address), method: :delete, remote: true, class: "edit-btn blue-btn user-dashboard-btn"%>
																</div>
															</div>
															<div class="nac-checkbox">
																<%#= radio_button :default_address, '',:id => "default_address#{address.id}", class: "css-checkbox" %> 
																<% if address.default_address %> 
																	<input type="radio" name="default_address" class="css-checkbox" checked="true"/>
																<% else %>
																	<input type="radio" name="default_address" class="css-checkbox"/>
																<% end %>
																<label for="radio5" id="<%=address.id%>" class="css-label radGroup2">Default delivery address</label>
															</div>
														</div>
													</div>
												<% end %>
											<% end %>
											<div class="col-md-4 col-sm-6 col-xs-12">
												<div class="newAdd-content addnewAdd-content">
													<a href="<%= new_address_path %>" data-remote="true">
														<span class="add-newAdd-span">+ Add a new address</span>
													</a>
												</div>
											</div>
										</div>
						    	</div>
						    </div>
								<div class="form"></div> -->
								<div class="profile"></div>
					    </div>
					    <div role="tabpanel" class="tab-pane review-tab" id="review">...</div>
					    
					  </div>
					</div>
				</div>
			</div>
		</div>
		<ul class="overlay-sm-links">
			<li><a href="#" class="facebook-bg"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
			<li><a href="#" class="instagram-bg"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
			<li><a href="#" class="twitter-bg"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
			<li><a href="#" class="pinterest-bg"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
		</ul>
	</div>
	<!-- /.banner-after-content -->
</div>

<script type="text/javascript">
	
</script>

app/views/users/user_lists.html.erb
<div class="main-content user-dashboard">
	<!-- /.banner-after-content -->
	<div class="banner-after-content">
		<div class="container">
			<div class="row">
				<%= render partial: "sidebar_menu" %>
				<div class="col-md-9 col-sm-8 col-xs-12">
					<div class="bac-right userDashboard-content">
						<div class="tab-content">
							<div class="edit-list-products"></div> 
							<div class="list-block">
					    	<div class="bac-heading">
									<h1>Lists <a href="#" class="d-newlist-btn" data-toggle="modal" data-target="#createListModal">Create a new list</a></h1>
								</div>
								<div class="udc-detail list-view-1">
									<% if @lists.present? %>
										<ul class="list-view">
											<% @lists.each do |list| %>
												<li>
													<div class="list-view-detail">
														<div class="list-view-img">
															<% if list.products.present? %>
																<a href="<%= edit_list_path(list) %>" class="edit-list-button" >
																	<%= image_tag(list.products.first.avatar.url, alt:"IMG")%>
																</a>
															<% end %>
														</div>
														<div class="list-view-text">
															<a href="<%= edit_list_path(list) %>" class="edit-list-button" >
																<label><%= list.name%></label>
															</a>
															<span class="createPost-span"><%= list.products.count %> books, created 1 day ago</span>
														</div>
													</div>
												</li>
											<% end %>
										</ul>
									<% else %>
										<p>Sorry you dont have any list available. </p>
									<% end %>
					    	</div>
					    </div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="modal sm-modal dashBoard-list-modal fade" id="createListModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content sm-overlay-detail">
      <div class="modal-header sm-overlay-head">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Create New List</h4>
      </div>
      <div class="modal-body sm-overlay-body">
      	<%= form_for :wish_list, remote: true, html: {class: "create-list-form form-inline studentMember-form dashboard-form"}, :url => create_list_path do |f| %>
      		<div class="form-group">
		        <%= f.text_field :name, class: 'form-control sm-form-fields', placeholder: 'Name for list' %>
		      </div>
	        <%= f.submit 'Save', class: 'btn btn-primary sm-account-btn' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
    $('li').removeClass('active');
    $(".<%= params[:action] %>").addClass("active");
	});

	// $('.create-list-form').bind('ajax:success', function(e, data, status, xhr){
 //  	$("#createListModal").modal('hide');
	//   toastr["success"]("<%=flash[:notice]%>")
 //  })
 //  	.bind("ajax:error",function(e, xhr, status, error){
 //    toastr["error"]("<%=flash[:alert]%>")
 //  });

 // $(document).ready(function() {
	//   return $(".create-list-form").on("ajax:success", function(e, data, status, xhr) {
	//     // return $(".create-list-form").append(xhr.responseText);
	//     $("#createListModal").modal('hide');
	//   	toastr["success"]("<%=flash[:notice]%>")
	//   }).on("ajax:error", function(e, xhr, status, error) {
	//     // return $(".create-list-form").append("<p>ERROR</p>");
	//     toastr["error"]("<%=flash[:alert]%>")
	//   });
	// });
</script>