config/routes.rb
Rails.application.routes.draw do

  get 'blogs/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { registrations: 'registrations', sessions: 'sessions' }
  root 'home#index'

  get 'users/edit_profile', to: 'users#edit_profile', as: :user_edit_profile
  get 'users/show/profile', to: 'users#show_profile', as: :user_profile
  put 'add_to_wish_list', to: 'users#add_to_wish_list', as: :add_to_wish_list
  get 'user/dashboard', to: 'users#user_dashboard', as: :user_dashboard
  get 'user/new_address', to: 'users#new_address', as: :new_address
  get 'user/address_book', to: 'users#address_book', as: :address_book
  get 'student_club', to: 'users#student_club', as: :student_club
  get 'user_lists', to: 'users#user_lists', as: :user_lists
  post 'user/lists', to: 'users#create_list', as: :create_list
  get 'user/:id/lists', to: 'users#edit_list', as: :edit_list
  delete 'remove/list/product/:id', to: 'users#remove_from_list', as: :remove_from_list
  get 'my/orders', to: 'users#show_orders', as: :show_orders
  get 'order/:id', to: 'users#order_details', as: :order_details
  post 'user/new/address', to: 'users#add_new_address', as: :add_new_address
  get 'edit/:id/address', to: 'users#edit_address', as: :edit_address
  patch 'edit/:id/address', to: 'users#update_address', as: :update_address
  delete 'remove/address/:id', to: 'users#destroy_address', as: :destroy_address
  put '/set/default_address', to: 'users#set_default_address'
  get 'edit/:id/student_profile', to: 'users#edit_student_club', as: :edit_student_club
  put 'edit/:id/student_profile', to: 'users#update_student_club', as: :update_student_club
  get 'reviews', to: 'users#show_reviews', as: :reviews
  
  resources :products , only:[:index, :show]
  resources :blogs, only:[:index, :show]

  get 'terms_and_conditions', to: "requests#terms_and_conditions"
  get 'privacy_policy', to: "requests#privacy_policy"
  get "new_book_request", to: "requests#book_request_new"
  post 'book_requests', to: "requests#book_request_create"
  get "study_abroad", to: "requests#study_abroad_new"
  post 'study_abroads', to: "requests#study_abroad_create"
  get 'publish_request', to: 'requests#publish_requests_new'
  post 'publish_requests', to: 'requests#publish_requests_create'
  get 'bulk_order_info', to: 'requests#bulk_order_info'
  get 'new/student/membership', to: 'requests#new_student_membership_request', as: :new_student_membership
  post 'student/membership/step/one', to: 'requests#student_membership_step_one_create', as: :student_membership_step_one
  put 'student/membership/update', to: 'requests#student_membership_update', as: :student_membership_update
  get 'advertise', to: 'requests#advertise'
  post 'advertise_enquiry_create', to: 'requests#advertise_enquiry_create'

  resources :requests, :path => '', only:[:none] do 
    collection do
      get 'aboutus', to: 'faqs/aboutus_faqs'
      get 'bulk_order_faqs', to: 'faqs/bulkOrder_faqs'
      get 'publish_faqs', to: 'faqs/publish_faqs'
      get 'student_membership_faqs', to: 'faqs/student_membership_faqs'
      get 'forget_password_faqs', to: 'faqs/forget_password_faqs'
      get 'publisher_author_guidelines_faqs', to: 'faqs/publisher_author_guidelines_faqs'
      get 'shipping_delivary_faqs', to: 'faqs/shipping_delivary_faqs'
      get 'request_book_faqs', to: 'faqs/request_book_faqs'
      get 'shipping_rates_faqs', to: 'faqs/shipping_rates_faqs'
      get 'careers', to: 'requests#careers'
      get 'contact_us', to: 'requests#contact_us'
      post 'contact_us', to: 'requests#create_new_contact_request'
      get 'bulk_order_discounts', to: 'requests#bulk_order_discounts'
      post 'create_bulk_order_discount', to: 'requests#create_bulk_order_discount'
    end
  end

  resources :carts, only:[:none] do
    member do 
      put 'add_to_cart'
      put 'increase_quantity'
      put 'decrease_quantity'
      put 'decrease_quantity_cart'
      put 'increase_quantity_cart'
    end

    collection do 
      get 'show', as: :cart
    end 
  end

  resources :orders, only: [:create]
  get 'check_out', to: 'orders#check_out', as: :check_out

  resources :reviews, only:[:update, :destroy, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
	include RequestsHelper
	before_action :get_social_networks

	def bulk_order_info	
	end

	# ==============study abroad================
	def study_abroad_new
		@new_request = StudyAbroad.new
	end

	def study_abroad_create
		@new_request = StudyAbroad.create(study_abroad_params)
	end
	# ==============study abroad================

	# ==============publish request=============
	def publish_requests_new
  	@new_request = PublishRequest.new
	end

	def publish_requests_create
		@new_request = PublishRequest.create(publish_request_params)
	end
	# ==============publish request=============

	# ==============book request================
	def book_request_new
		@new_request = BookRequest.new
	end

	def book_request_create
		@new_request = BookRequest.create(book_request_params)
	end
	# ==============book request================

	# ==============advertise================
	def advertise
		@main_view = params[:main_view]
	end

	def advertise_enquiry_create
		@advertise = Advertise.create(advertise_params)
	end

	# ==============advertise================


	# ==============student membership==========
	def new_student_membership_request
		@profile = StudentProfile.new
	end

	def student_membership_step_one_create
		@profile = StudentProfile.create(student_membership_params)
		if current_user.present? && !current_user.student_profile.present?
			current_user.user_type = 1
			@profile.user = current_user
			flash[:info] = "Profile created Successfully!"
		elsif !current_user.present?
			@name = params[:student_profile][:name].split(" ")
			resource.first_name = @name[0]
			resource.last_name = @name[1]
			resource.email = params[:student_profile][:email]
			resource.email_confirmation = params[:student_profile][:email]
			resource.password = params[:student_profile][:password]
			resource.password_confirmation = params[:student_profile][:password]
			resource.user_type = 1
			if resource.save
				sign_in(resource)
        flash[:info] = "Signed-up successfully!"
        @resource_created = true
      else
      	@resource_created = false
			end
			@profile.user = resource if resource.persisted?
		end
	end

	def student_membership_update 
		@profile = StudentProfile.find params[:student_profile][:profile_id]
		@profile.update(student_membership_update_params)
	end

	# ==============student membership==========
	def aboutus
		render 'requests/faqs/aboutus'
	end

	def bulk_order_faqs
		render 'requests/faqs/bulkOrder_faqs'
	end

	def publish_faqs
		render 'requests/faqs/publish_faqs'
	end

	def student_membership_faqs
		render 'requests/faqs/student_membership_faqs'
	end

	def forget_password_faqs
    render 'requests/faqs/forgot_password_faqs'
  end

  def publisher_author_guidelines_faqs
  	render 'requests/faqs/publisher_author_guidelines_faqs'
  end

  def shipping_delivary_faqs
  	render 'requests/faqs/shipping_delivary_faqs'
  end

  def request_book_faqs
  	render 'requests/faqs/request_book_faqs'
  end

  def shipping_rates_faqs
  	render 'requests/faqs/shipping_rates_faqs'
  end

  def terms_and_conditions
  	render 'requests/faqs/terms_and_conditions'
  end

  def privacy_policy
  	render 'requests/faqs/privacy_policy'
  end

  def careers
  end

  def contact_us
  	@contact = Contact.new
  end

  def create_new_contact_request
  	@contact = Contact.new(contact_params)
  	if @contact.save
  		flash[:notice] = 'Your request has been submitted successfully. We\'ll contact you soon'
      ContactMailer.contact(@contact).deliver_later
  		redirect_to :back 
  	else
  		flash[:alert] = @contact.errors.full_messages.join('<br>'.html_safe)
  		render :contact_us
  	end
  end

  def bulk_order_discounts
  	render 'requests/bulk_order_discounts'
  end

  def create_bulk_order_discount
  	@bulk_order_discount = BulkOrderDiscount.new(bulk_order_discounts_params)
  	other_information = params[:other_information]
  	@others = []
  	other_information.each do |info|
  		other_info = OtherInformation.new()
  		other_info.book_title = info[:book_title]
  		other_info.author = info[:author]
  		other_info.publisher = info[:publisher]
  		other_info.quantity = info[:quantity]
  		other_info.save
  		@others.push(other_info)
  	end
  	@bulk_order_discount.other_informations = @others
  	if @bulk_order_discount.save
  		flash[:info] = "Your request has been submitted successfully!"
  		redirect_to :back
  	else
  		flash[:alert] = @bulk_order_discount.errors.full_messages.join('<br>'.html_safe)
  		render :bulk_order_discounts
  	end
  end

	private

	def study_abroad_params
    params.require(:study_abroad).permit(:full_name, :interested_study_field, :current_education, :city, :email, :mobile_no, :message)
  end

  def publish_request_params
    params.require(:publish_request).permit(:full_name, :primary_subj_area, :job_title, :city, :email, :mobile_no, :project_summary)
  end

  def book_request_params
    params.require(:book_request).permit(:book_title, :author, :email, :full_name, :mobile_no, :comments)
  end

  def student_membership_params
  	params.require(:student_profile).permit(:date_of_birth, :gender , :name, :email, :password, :institution_name, :current_educational_level, :area_of_study, :year_of_study, :course_length, :student_id, :mobile_no)
  end

  def student_membership_update_params
  	params.require(:student_profile).permit(:date_of_birth, :gender , :name, :email, :password, :institution_name, :current_educational_level, :area_of_study, :year_of_study, :course_length, :student_id, :mobile_no)
  end

  def advertise_params
  	params.require(:advertise).permit(:name, :email, :contact_no, :message, :company)
  end

  def bulk_order_discounts_params
  	params.require(:bulk_order_discount).permit(:full_name, :company, :city, :country, :phone_number, :email, :message)
  end

  def other_information_params
  	params.require(:other_information).permit(:book_title, :author, :publisher, :quantity)
  end

  def contact_params
  	params.require(:contact).permit(:name, :email, :phone_no, :company, :message)
  end

  def get_social_networks
  	@social = SocialShare.first
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
	def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/requests/advertise.html.erb
<div class="advertise-page">
	<div class="container">
		<div class="advertise-container">
			<% if @main_view.present? %>
				<%= render partial: '/requests/advertise_info'%>
			<% else %>
				<%= render partial: '/requests/advertise_form'%>
			<% end %>
		</div>
	</div>
</div>

app/views/requests/book_request_new.html.erb
<div class="main-content requestbook-content">
	<!-- /.banner-requestbook -->
	<div class="banner-site banner-requestbook">
		<div class="br-overlay-1">
			<div class="br-overlay-inner">
				<h1>DROPPINGO</h1>
				<a href="#">Request a book</a>
			</div>
		</div>
		<div class="br-overlay-2">
			<div class="br-overlay-inner">
				<p>CAN'T FIND A BOOK YOU NEED?</p>
				<p>LET US DO THE SEARCHING FOR YOU</p>
			</div>
		</div>
		<ul class="overlay-sm-links">
			<li><a href="<%= SocialShare.first.fb_link %>" class="facebook-bg" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
			<li><a href="<%= SocialShare.first.instagram_link %>" class="instagram-bg" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
			<li><a href="<%= SocialShare.first.twitter_link %>" class="twitter-bg" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
			<li><a href="<%= SocialShare.first.pinterest_link %>" class="pinterest-bg" target="_blank"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
		</ul>
	</div>
	<!-- /.banner-requestbook -->
	<!-- /.banner-after-content -->
	<div class="banner-after-content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-3 col-sm-4 col-xs-12">
					<div class="bac-left requestbook-bac-left">
						<div class="bac-left-img">
							<%= image_tag("multi-books.png", alt: "IMG")%>
						</div>
						<div class="bac-right-detail">
							<h1>REQUEST A BOOK FORM</h1>
							<%= form_for BookRequest.new, remote: true, html: {class: "bac-publish-form", name: "bookRequestForm"}, :url => book_requests_path, method: :post do |f| %>
								<div id="error-div"></div>
	    					<div class="row">
									<div class="col-md-12">
										<div class="form-group">
											<%= f.text_field :book_title, id: "book_title", class: "form-control publish-fields", placeholder: "book title" %>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-12">
										<div class="form-group">
											<%= f.text_field :author, id: "author", class: "form-control publish-fields", placeholder: "author" %>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-12">
										<div class="form-group">
											<%= f.text_field :full_name, id: "full_name", class: "form-control publish-fields", placeholder: "Full Name" %>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-12">
										<div class="form-group">
											<div class="email_error"></div>
											<%= f.text_field :email, id: "email", class: "form-control publish-fields", placeholder: "Email ID" %>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-12">
										<div class="form-group">
											<%= f.text_field :mobile_no, id: "mobile_no", class: "form-control publish-fields", placeholder: "Mobile No" %>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-12">
										<div class="form-group">
											<%= f.text_field :comments, id: "comments", class: "form-control publish-fields", placeholder: "Comments" %>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-12">
										<%= f.submit 'Submit', :class => 'publish-btn' %>
									</div>
								</div>
	    				<% end %>
						</div>
						<div class="overlay-message">
				    	<div class="overlay-msg-inner">
				      	<span><i class="fa fa-check" aria-hidden="true"></i></span>
				      	<h1>Thank You!</h1>
				      	<p>Your message has been received, we'll be in touch very soon</p>
				     	</div>
				    </div>
					</div>
				</div>
				<div class="col-md-9 col-sm-8 col-xs-12">
					<div class="bac-right requestbook-bac-right">
						<div class="bac-heading">
							<h1>Request a Book</h1>
						</div>
						<div class="bac-detail">
							<p>Can't find a book you're looking for? Let us know and we'll try and buy it for you.</p>
							<p>It can take a few days to purchase and make the book available.</p>
							<label>How Do I Make Requests?</label>
							<p>There are many ways to request books from us. The simplest and quickest method is by filling and submitting the Request a book form on the left. Alternatively, we can take your requests via <a href="#">email or phone</a>.</p>
							<ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- /.banner-after-content -->
</div>

<script type="text/javascript">
// $.ajax({
//     url:  "/book_requests",
//     type: "POST",
//     dataType: "json",
//     success: function(data) { 
//        var r = $.parseJSON(data);
//        console.log(r)//This is where Your users are
//     }
// });
// $(document).ready(function(){
// 	 $(document).ajaxSuccess( function(data) {
// 	 		console.log(data);
// 	 		alert(data);
// 	 })
//    $(document).ajaxError( function(data) {alert(data);} )
//     $('.publish-btn').closest('form').on('ajax:success', function() {
//       console.log('ajax:success!');
//     });

//     $('.publish-btn').bind("ajax:success", function() {
//     console.log( 'test' );
//     });
// });
</script>

app/views/requests/bulk_order_info.html.erb
<div class="main-content bulkOrder-content">
	<!-- /.banner-after-content -->
	<div class="banner-after-content">
		<div class="container">
			<div class="row">
				<div class="col-md-9 col-sm-8 col-xs-12">
					<div class="bac-left bac-left-common">
						<div class="bac-heading">
							<h1>Bulk Order Discounts</h1>
						</div>
						<div class="bac-detail">
							<h4>About Bulk Ordering</h4>
							<h5>Placing a Bulk Order on Droppingo</h5>
							<p>For assistance with placing a bulk order, please contact our Business Support Department on <a href="#">help@droppingo.com</a></p>
							<p>If you would like to place a bulk order, please fill out the Request for Pricing form completely, including the following details</p>
							<ul class="publish-follow-list dashes-list">
								<li>Name, phone number, and company/institution.</li>
								<li>Date when the titles need to arrive (MM/DD/YYYY) - Full date required.</li>
								<li>Ship-to address (including City & Province)</li>
								<li>If you plan to pay with a Purchase Order, please mention that in the "Additional Message" section of the Request for pricing form.</li>
							</ul>
							<p>Depending on current volume Droppingo Customer Service will respond within 1 Business Day from receipt of your request. (Response time may increase or decrease depending on the size of the request).</p>
							<h5>Accepted Payment Methods</h5>
							<p>Droppingo accepts all major credit cards, debit cards, pay orders, cheques and online bank transfers. In addition, schools and institutions may purchase on a purchase order.</p>
							<h5>Purchase Orders</h5>
							<p>When ordering on Droppingo.com, please mention that in the "Additional Message" section of the Request for Pricing form.</p>
						</div>
					</div>
				</div>
				<div class="col-md-3 col-sm-4 col-xs-12">
					<div class="bac-right bac-right-common">
						<div class="other-faqs">
							<h1>Other FAQS</h1>
							<ul class="otherFaqs-list">
								<li><a href="<%= student_membership_faqs_requests_path %>">Student Membership</a></li>
								<li><a href="<%= publish_faqs_requests_path %>">Publish with Droppingo</a></li>
								<li><a href="<%= request_book_faqs_requests_path %>">Request a Book</a></li>
								<li><a href="<%= publisher_author_guidelines_faqs_requests_path%>">Publisher & Author Guidelines</a></li>
								<li><a href="<%= forget_password_faqs_requests_path %>">Forgot Password</a></li>
								<li><a href="<%= bulk_order_info_path %>">Bulk Order Discounts</a></li>
								<li><a href="<%= shipping_delivary_faqs_requests_path %>">Shipping & Delivery</a></li>
							</ul>
						</div>
						<div class="contact-publisher">
							<h1>Contact Us</h1>
							<ul class="contactUs-list">
								<li class="cl-mail"><a href="#">Email Us</a></li>
								<li class="cl-phone">
									<a href="#">Call Us</a>
									<p><span>If you can't find what you're looking for, contact our Customer Service on 03-111-123-456</span></p>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- /.banner-after-content -->
</div>

app/views/requests/new_student_membership_request.html.erb
<div class="main-content studentMember-content">
	<!-- /.banner-publisher -->
	<div class="banner-site banner-studentMember">
		<div class="container">
			<div class="row">
				<div class="col-md-12 text-center">
					<a href="#" class="sm-account-btn sm-account-btn-1" data-toggle="modal" data-target="#myModal-1">Create An Account</a>
				</div>
			</div>
			<ul class="overlay-sm-links">
				<li><a href="#" class="facebook-bg"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
				<li><a href="#" class="instagram-bg"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
				<li><a href="#" class="twitter-bg"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
				<li><a href="#" class="pinterest-bg"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
			</ul>
		</div>
	</div>
	<!-- /.banner-publisher -->

	<!-- Modal -->
	<div class="modal fade sm-modal" id="myModal-1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="sm-overlay-detail">
					<div class="sm-overlay-head">
						<h4>YOUR DETAILS</h4>
						<button type="button" class="close-btn close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					</div>
					<div class="sm-overlay-body">
						<%= form_for :student_profile, remote: true, html: {class: "studentMember-form"}, :url => student_membership_step_one_path do |f| %>
							<div class="row">
								<div class="col-md-12">	
									<div class="form-group">
										<% if current_user.present? %>
											<%= f.text_field :name, class: "form-control sm-form-fields", value: current_user.first_name+ " " +current_user.last_name, disabled: (true)%>
											<%= f.hidden_field :name, value: current_user.first_name+ " " +current_user.last_name %>
										<% else %>
											<%= f.text_field :name, class: "form-control sm-form-fields", placeholder: "Full Name"%>
										<% end %>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-12">	
									<div class="form-group">
										<% if current_user.present? %>
											<%= f.email_field :email, class: "form-control sm-form-fields", value: current_user.email, disabled: (true)%>
											<%= f.hidden_field :email, value: current_user.email %>
										<% else %>
											<%= f.email_field :email, class: "form-control sm-form-fields", placeholder: "Email"%>
										<% end %>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-12">	
									<div class="form-group">	
										<%= f.password_field :password, class: "form-control sm-form-fields", placeholder: "Password", disabled: (true if current_user.present?) %>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-12">
									<div class="form-group">
										<ul class="gender-option">
											<li class="">
												<div class="radio">
													<label>
														<%= f.radio_button :gender, 'male', :id => 'gender' %> Male
													</label>
												</div>
											</li>
											<li>
												<div class="radio">
													<label>
														<%= f.radio_button :gender, 'female', :id => 'gender' %> Female
													</label>
												</div>
											</li>
										</ul>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-md-3 col-sm-3 col-xs-12">
											<label class="birthday-label">Birthday</label>
										</div>
										<div class="col-md-9 col-sm-9 col-xs-12">
											<div class="form-group sm-birthday-set">
												<%= f.date_select(:date_of_birth, :order => [:month, :day, :year], :start_year=>1970, :class => "form-control sm-form-fields", placeholder: "Birth Date")%>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-12">
									<%= f.submit 'Create Account', :class => 'btn sm-account-btn' %>
									<div class="createAccout-content">
										<p class="terms-para">By submitting this form, you are agreeing to our 
											<span><a href="#">Terms and Conditions</a></span>
										</p>
										<p class="login-para">Have an account already? 
											<span><a href="#">LOG IN</a></span>
										</p>
									</div>
								</div>
							</div>
						<% end %>
					</div>
				</div>
	    </div>
	  </div>
	</div>


	<div class="modal fade sm-modal sm-modal-2" id="myModal-2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-backdrop="static" data-keyboard="false">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="sm-overlay-detail">
					<div class="sm-overlay-head">
						<h4>YOUR DETAILS</h4>
						<button type="button" class="close-btn close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					</div>
					<div class="sm-overlay-body">
						<%= form_for :student_profile, remote: true, method: :put, html: {class: "studentMember-form"}, :url => student_membership_update_path do |f| %>
							<%= f.hidden_field :profile_id, :class => "profile_id" %>
							<div class="row">
								<div class="col-md-12">	
									<div class="form-group">
										<%= f.text_field :institution_name, class: "form-control sm-form-fields", placeholder: "NAME OF INSTITUTION"%>
									</div>
								</div>
							</div>

							<div class="row">
								<div class="col-md-12">	
									<div class="form-group sm-birthday-set">
										<%= f.select :current_educational_level, options_for_select([["CURRENT EDUCATION LEVEL", ""], "Bachelors Degree", "Masters", "PhD", "Others"]), :class => 'form-control sm-form-fields' %>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-12">	
									<div class="form-group">
										<%= f.text_field :area_of_study, class: "form-control sm-form-fields", placeholder: "COURSE / AREA OF STUDY"%>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-6 col-sm-6 col-xs-12">	
									<div class="form-group sm-birthday-set">
										<%= f.select :year_of_study, options_for_select([["YEAR OF STUDY", ""], "Freshmen", "Sophomor", "Junior", "Senior"]), :class => 'form-control sm-form-fields' %>
									</div>
								</div>
								<div class="col-md-6 col-sm-6 col-xs-12">	
									<div class="form-group sm-birthday-set">
										<%= f.select :course_length, options_for_select([["COURSE LENGTH", ""], "1", "2", "3", "4"]), :class => 'form-control sm-form-fields' %>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-12">	
									<div class="form-group">
										<%= f.text_field :student_id, class: "form-control sm-form-fields", placeholder: "STUDENT ID / ROLL NO."%>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-12">	
									<div class="form-group">
										<%= f.text_field :mobile_no, class: "form-control sm-form-fields", placeholder: "MOBILE NO"%>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-12">
									<%= f.submit 'SUBMIT', :class => 'btn sm-account-btn' %>
								</div>
							</div>
						<% end %>
					</div>
					<div class="sm-overlay-footer">
						<p class="login-email"></p><p>- <a href="<%= destroy_user_session_path %>" data-method="delete">Logout</a></p>
					</div>
				</div>
	    </div>
	  </div>
	</div>


	<!-- /.banner-after-content -->
	<div class="banner-after-content">
		<div class="container">
			<div class="row">
				<div class="col-md-11">
					<div class="bac-left bac-left-common">
						<div class="bac-heading">
							<h1>Droppingo Student Membership</h1>
						</div>
						<div class="bac-detail">
							<h4>Join Pakistan's largest community of School, College and University students today! Your portal to a better student life!</h4>
							<h4>Our Aims</h4>
							<ul class="publish-follow-list">
								<li>To help students save money and better manage their finances.</li>
								<li>To offer students amazing deals, offers & discounts on the brands they love.</li>
								<li>To help students find jobs.</li>
								<li>To help students make well-informed career and life choices.</li>
							</ul>
							<h4>In short, we exist to help students.</h4>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- /.banner-after-content -->
</div>

<script type="text/javascript">
	var selector = '.gender-option li ';
	$(selector).on('click', function(){
    $(selector).removeClass('active');
    $(this).addClass('active');
	});
</script>

app/views/requests/student_membership_update.js.erb
<% if @profile.save %>
	<% flash[:info] = "Student profile has been updated successfully." %>
	<% if params[:student_profile][:redirect].present? %>
		window.location.href = "<%= student_club_path %>"
	<% else %>
		$('#myModal-2').remove();
		window.location.href = "<%= user_profile_path %>";
	<% end %>
<% else %>
	toastr["error"]("Please provide all fields marked with *");
<% end %>