config/routes.rb
Rails.application.routes.draw do

  get 'blogs/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { registrations: 'registrations', sessions: 'sessions' }
  root 'home#index'

  get 'users/edit_profile', to: 'users#edit_profile', as: :user_edit_profile
  get 'users/show/profile', to: 'users#show_profile', as: :user_profile
  put 'add_to_wish_list', to: 'users#add_to_wish_list', as: :add_to_wish_list
  get 'user/dashboard', to: 'users#user_dashboard', as: :user_dashboard
  get 'user/new_address', to: 'users#new_address', as: :new_address
  get 'user/address_book', to: 'users#address_book', as: :address_book
  get 'student_club', to: 'users#student_club', as: :student_club
  get 'user_lists', to: 'users#user_lists', as: :user_lists
  post 'user/lists', to: 'users#create_list', as: :create_list
  get 'user/:id/lists', to: 'users#edit_list', as: :edit_list
  delete 'remove/list/product/:id', to: 'users#remove_from_list', as: :remove_from_list
  get 'my/orders', to: 'users#show_orders', as: :show_orders
  get 'order/:id', to: 'users#order_details', as: :order_details
  post 'user/new/address', to: 'users#add_new_address', as: :add_new_address
  get 'edit/:id/address', to: 'users#edit_address', as: :edit_address
  patch 'edit/:id/address', to: 'users#update_address', as: :update_address
  delete 'remove/address/:id', to: 'users#destroy_address', as: :destroy_address
  put '/set/default_address', to: 'users#set_default_address'
  get 'edit/:id/student_profile', to: 'users#edit_student_club', as: :edit_student_club
  put 'edit/:id/student_profile', to: 'users#update_student_club', as: :update_student_club
  get 'reviews', to: 'users#show_reviews', as: :reviews
  
  resources :products , only:[:index, :show]
  resources :blogs, only:[:index, :show]

  get 'terms_and_conditions', to: "requests#terms_and_conditions"
  get 'privacy_policy', to: "requests#privacy_policy"
  get "new_book_request", to: "requests#book_request_new"
  post 'book_requests', to: "requests#book_request_create"
  get "study_abroad", to: "requests#study_abroad_new"
  post 'study_abroads', to: "requests#study_abroad_create"
  get 'publish_request', to: 'requests#publish_requests_new'
  post 'publish_requests', to: 'requests#publish_requests_create'
  get 'bulk_order_info', to: 'requests#bulk_order_info'
  get 'new/student/membership', to: 'requests#new_student_membership_request', as: :new_student_membership
  post 'student/membership/step/one', to: 'requests#student_membership_step_one_create', as: :student_membership_step_one
  put 'student/membership/update', to: 'requests#student_membership_update', as: :student_membership_update
  get 'advertise', to: 'requests#advertise'
  post 'advertise_enquiry_create', to: 'requests#advertise_enquiry_create'

  resources :requests, :path => '', only:[:none] do 
    collection do
      get 'aboutus', to: 'faqs/aboutus_faqs'
      get 'bulk_order_faqs', to: 'faqs/bulkOrder_faqs'
      get 'publish_faqs', to: 'faqs/publish_faqs'
      get 'student_membership_faqs', to: 'faqs/student_membership_faqs'
      get 'forget_password_faqs', to: 'faqs/forget_password_faqs'
      get 'publisher_author_guidelines_faqs', to: 'faqs/publisher_author_guidelines_faqs'
      get 'shipping_delivary_faqs', to: 'faqs/shipping_delivary_faqs'
      get 'request_book_faqs', to: 'faqs/request_book_faqs'
      get 'shipping_rates_faqs', to: 'faqs/shipping_rates_faqs'
      get 'careers', to: 'requests#careers'
      get 'contact_us', to: 'requests#contact_us'
      post 'contact_us', to: 'requests#create_new_contact_request'
      get 'bulk_order_discounts', to: 'requests#bulk_order_discounts'
      post 'create_bulk_order_discount', to: 'requests#create_bulk_order_discount'
    end
  end

  resources :carts, only:[:none] do
    member do 
      put 'add_to_cart'
      put 'increase_quantity'
      put 'decrease_quantity'
      put 'decrease_quantity_cart'
      put 'increase_quantity_cart'
    end

    collection do 
      get 'show', as: :cart
    end 
  end

  resources :orders, only: [:create]
  get 'check_out', to: 'orders#check_out', as: :check_out

  resources :reviews, only:[:update, :destroy, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :categories_products, dependent: :destroy
	has_many :categories, through: :categories_products

	has_many :carts_product, dependent: :destroy
	has_many :carts, through: :carts_product
	
	has_many :orders_product, dependent: :destroy
	has_many :order, through: :orders_product

	has_many :products_tags, dependent: :destroy
	has_many :tags, through: :products_tags

	has_many :cart_items, dependent: :destroy

	has_many :products_wish_lists, dependent: :destroy
	has_many :wish_lists, through: :products_wish_lists

  has_many :reviews, dependent: :destroy

	accepts_nested_attributes_for :categories
	accepts_nested_attributes_for :tags, allow_destroy: true

	has_attached_file :avatar, styles: { medium: "300x300#", thumb: "100x100#" }, default_url: "/assets/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  # validates :iban, uniqueness: true
  # after_save ThinkingSphinx::RealTime.callback_for(:product)
  after_create :add_parent_category

  default_scope { order(created_at: :desc) }

  searchable :auto_index => true do
    text :author
    text :title
    string :title    
    integer :category_ids, :multiple => true
    float :price
    text :categories do 
      categories.map(&:name)
    end
  end

  # add parent categories to product after creation
  def add_parent_category
    @categories = self.categories
    @cat = Array.new
    @categories.each do |category|
      @cat.push << category.id
      get_parent(category.parent)
    end
    self.category_ids = @cat.uniq
    self.save
  end


  def get_parent(cat)
	  return if cat.nil? 
	  @cat.push(cat.id)
	  get_parent(cat.parent)    
	end 

  def self.product_of_month(root)
    roots = Category.where(parent_id: nil).where.not(id: root.id)
    @product = root.products.joins(:categories).where('products.product_of_the_month = ? AND categories.name NOT IN (?)', true, roots.collect(&:name)).last
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :set_product, only:[:show]
	

	def index
		if params[:category_id].present?
			@category = Category.find params[:category_id]
		else
			@category = nil
		end
		@product_sort_by = params[:sort_by]
		count = Product.count
		@search = Sunspot.search(Product) do
	    fulltext params[:search] do 
	    	fields(:title, :author)
	    end
			# order_by(:title, :desc) if params[:sort_by] == "Title"
			paginate :page => 1, :per_page => count
			if params[:sort_by] == "Price Low-High"
	    	order_by(:price, :asc)
	    elsif params[:sort_by] == "Price High-Low"
	    	order_by(:price, :desc)
	    elsif params[:sort_by] == "Title A-Z"
	    	order_by(:title, :asc)
	    elsif params[:sort_by] == "Title Z-A"
	    	order_by(:title, :desc)
	    end
	    facet :price, :range => 0..5000, :range_interval => 1000
      with(:price, Range.new(*params[:price_range].split("-").map(&:to_i))) if params[:price_range].present?
	    with(:category_ids, params[:category_id]) if params[:category_id].present?
	  end
	  @price_range = params[:price_range] 
	  @view_type = params[:view_type].to_i
	  if params[:per_page].present?
	  	@products = Kaminari.paginate_array(@search.results).page((params[:page] rescue 1)).per(params[:per_page])
	  	@products_per_page = params[:per_page]
	  else
	  	@products = Kaminari.paginate_array(@search.results).page((params[:page] rescue 1)).per(20)
	  end
	end

	def show
		@product
		tag = @product.tags.last
		category = @product.categories.last
		if tag.present? 
			@same_tag_products = tag.products.where.not(id: @product.id).last(6)
		end
		@cart_item = @cart.cart_items.find_or_initialize_by(product_id: @product.id)
		if @cart_item.present? && @cart_item.quantity.present?
			@quantity = @cart_item.quantity
		else
			@quantity = 1
		end
		# current user review
		@review = @product.reviews.where(user_id: current_user.id) if current_user.present?
		
		# total reviews
		@all_reviews = @product.reviews
		@all_reviews_rating = @product.reviews.pluck(:rating)
		@sum = @all_reviews_rating.sum
		@rating = @sum/@all_reviews_rating.count if @all_reviews_rating.present?

		@social = SocialShare.first
	end

	private
	def set_product
		@product = Product.find(params[:id])
	end

end

app/helpers/products_helper.rb
module ProductsHelper

	def render_breadcrumb_links
    breadncrumb = "<a href=#{products_path(:category_id => @category.id)}> #{@category.name}</a>"
    @cat = @category
    while !get_parent(@cat).nil?
      breadncrumb = "<a href=#{products_path(:category_id => @cat.id)}> #{@cat.name} </a>" + "<p style='margin-right: 5px;'> / </p> " + breadncrumb
    end
    breadncrumb
  end

  def get_parent(cat)
    @cat = @cat.parent
  end

  

end

app/views/products/_product_list_view.html.erb
<div class="sc-books books-show-list">
	<% @products.each do |product| %>
		<div class="row">
			<div class="col-md-2 col-sm-4 col-xs-6">
				<a href="<%= product_path(product) %>">
					<div class="commonblock-container features-container">
						<div class="commonblock-img features-img site-img-setting">
			 				<%= image_tag(product.avatar.url, alt: 'IMG') %>
			 			</div>
			 		</div>
			 	</a>
			</div>
			<div class="col-md-10 col-sm-8 col-xs-6">
				<div class="commonblock-detail proView-detail pd-about-book">
					<h1><%= product.title %></h1>
					<p class="author-name">By: <span><%= product.author %></span></p>
					<p class="publisher-name">Publisher: <span><%= product.publisher %></span></p>
					<p class="isbn-no">ISBN: <span><%= product.isbn %></span></p>
					<p class="isbn-no">Price: <span><%= product.price %></span></p>
				</div>
			</div>
		</div>
		<hr>
	<% end %>
</div>

app/views/products/_products.html.erb
<div class="sc-books">
	<% if @view_type == 2 %>
		<%= render partial: 'product_list_view' %>
	<% else %>
		<div class="update-view">										
			<div class="sc-books">

				<% products.each_slice(5) do |product| %>
					<div class="features-block sc-books-content">
						<ul>
							<% product.each do |pro| %>
								<li>
									<a href="<%= product_path(pro) %>">
										<div class="commonblock-container features-container">
											<div class="commonblock-img features-img site-img-setting">
												<%= image_tag(pro.avatar.url, alt: "IMG", draggable: false)%>
											</div>
											<div class="commonblock-detail features-detail">
												<p><%= pro.title %>:by <%= pro.author %></p>
												<span class="price-books">Rs <%= pro.price %></span>
											</div>
										</div>
									</a>
								</li>
							<% end %>
						</ul>
					</div>
				<% end %>
				<% if !products.present? %>
					<span class="no-books">No books available</span>
				<% end %> 
			</div>
		</div>
	<% end %>
</div>

app/views/products/products_view.html.erb
<%= render partial: 'products/products', locals: {category: @category, products: @products}%>

app/views/products/show.html.erb
	
<!-- <meta property="og:title" content="<%= @product.title %>" />
<meta property="og:type" content="book" />
<meta property="og:image" content="http://droppingo.mashup.li<%= @product.avatar.url %>" />
<meta property="og:url" content="http://droppingo.mashup.li/products/<%= @product.id %>" />
<meta property="og:description" content="<%= @product.description %>" /> -->
<!-- <div id="fb-root"></div> -->
<div class="main-content productView-content">
	<!-- /.proView-block -->
	<div class="common-block proView-block">
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="commonblock-img proView-img site-img-setting">
						<img src="<%= @product.avatar.url %>" alt="IMG">
					</div>
					<div class="proView-viewers text-center">
						<span class="viewer-star">
							<div id="total-rating"></div>
						</span>
						<span class="viewer-review"><%= @all_reviews_rating.count %> Reviews</span>
					</div>
				</div>
				<div class="col-md-8 col-sm-8 col-xs-12">
					<div class="commonblock-detail proView-detail pd-about-book">
						<div class="proView-wishlist">
						<!-- add_to_wish_list_path(@product) -->
							<% if current_user.present? %>
								<a href="#" class="blue-btn wishlist-btn" data-toggle="modal" data-target="#addToListModal">Add to List</a>
							<% end %>
							<h1><%= @product.title %></h1>
						</div>
						<p class="author-name">By: <span><%= @product.author %></span></p>
						<p class="publisher-name">Publisher: <span><%= @product.publisher %></span></p>
						<p class="isbn-no">ISBN: <span><%= @product.isbn %></span></p>
						<div class="sc-sort proView-order">
							<div class="row">
								<div class="col-md-8 col-sm-6 col-xs-12">
									<div class="proView-order-stock">
										<label>Paperback</label>
										<span class="in-stock"><i class="fa fa-check" aria-hidden="true"></i> In Stock</span>
										<form class="pro-quantity-form">
											<label>Quantity</label>
											<div class="quantity-group">
												<button><%= link_to '-', decrease_quantity_cart_path(@product), :method => :put, remote: true %></button>
												<input type="text" class="quantity-field" value="<%= @quantity %>" disabled>
												<button><%= link_to '+', increase_quantity_cart_path(@product), :method => :put, remote: true %></button>
											</div>
										</form>
									</div>
								</div>
								<div class="col-md-4 col-sm-6 col-xs-12">
									<div class="proView-order-cart text-center">
										<label>Rs. <%= @product.price %></label>
										<%= link_to 'Add To Cart', add_to_cart_cart_path(@product), :method => :put, remote: true %>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<ul class="overlay-sm-links">
			<li><a href="<%= @social.fb_link %>" class="facebook-bg" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
			<li><a href="<%= @social.instagram_link %>" class="instagram-bg" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
			<li><a href="<%= @social.twitter_link %>" class="twitter-bg" target="_blank"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
			<li><a href="<%= @social.pinterest_link %>" class="pinterest-bg" target="_blank"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
		</ul>
		<!-- <ul class="overlay-sm-links">
			<li class="fb-list">
				<div class="fb-share-button" data-href="http://droppingo.mashup.li/products/<%= @product.id %>" data-layout="button" data-size="small" data-mobile-iframe="true"></div>
				<a class="facebook-bg"><i class="fa fa-facebook" aria-hidden="true"></i></a>
			</li>

			<li class="insta-list">
				<a href="#" class="instagram-bg"><i class="fa fa-instagram" aria-hidden="true"></i></a>
			</li>

			<li class="tw-list">
				<iframe class="twitter-bg-1"
				  src="https://platform.twitter.com/widgets/tweet_button.html?size=l&
				  url=http://droppingo.mashup.li/products/<%= @product.id %>&related=twitterapi%2Ctwitter&text=<%=@product.title%>&hashtags=#{@product.title}&data-size=large"
				  width="140"
				  height="28"
				  title="<%= @product.title %>"
				  style="border: 0; overflow: hidden;">
					<i class="fa fa-twitter" aria-hidden="true"></i>
				</iframe>
				<a href="#" class="twitter-bg"><i class="fa fa-twitter" aria-hidden="true"></i></a>
			</li>
			<li class="pin-list">
				<a class="pinterest-bg" data-pin-do="buttonPin" href="https://www.pinterest.com/pin/create/button/?url=http://www.foodiecrush.com/2014/03/filet-mignon-with-porcini-mushroom-compound-butter/&media=https://s-media-cache-ak0.pinimg.com/736x/17/34/8e/17348e163a3212c06e61c41c4b22b87a.jpg&description=So%20delicious!" data-pin-custom="true"><i class="fa fa-pinterest-p" aria-hidden="true"></i>
				</a>
			</li>
		</ul> -->
	</div>
	<!-- /.proView-block -->
	<!-- /.itemBought-block -->
	<div class="common-block itemBought-block">
		<div class="container">
			<h3 class="productView-heading">Customers Who Bought This Item Also Bought</h3>
			<div class="sc-books">
				<div class="features-block sc-books-content">
					<div class="row">
						<% if @same_tag_products.present? %>
							<% @same_tag_products.each do |product| %>
								<div class="col-md-2 col-sm-4 col-xs-6">
									<div class="commonblock-container">
										<a href="<%= product_path(product) %>">
											<div class="commonblock-img features-img">
												<img src="<%= product.avatar.url %>" alt="IMG" draggable="false">
											</div>
											<div class="commonblock-detail features-detail">
												<p><%= product.title %></p>
												<span class="price-books">Rs <%= product.price %></span>
											</div>
										</a>
									</div>
								</div>
							<% end %>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- /.itemBought-block -->
	<!-- /.pro-overview-block -->
	<div class="common-block pro-overview-block">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="sc-sort pro-overview-list">
						<ul>
							<li><a href="#overview">overview</a></li>
							<li><a href="#details">product description</a></li>
							<li><a href="#related_sub">related subjects</a></li>
							<li><a href="#reviews">reviews</a></li>
						</ul>
					</div>
					<div class="pro-overview-detail">
						<div class="pro-inner-content pic-overview">
							<h3 class="productView-heading" id="overview">Overview</h3>
							<p><%= (@product.description).html_safe if @product.description.present? %></p>
						</div>
						<div class="pro-inner-content pic-descrip">
							<h3 class="productView-heading" id="details">Product Description</h3>
							<p>ISBN: <span><%= @product.isbn %></span></p>
							<p>Publisher: <span><%= @product.publisher %></span></p>
							<p>Author: <span><%= @product.author %></span></p>
							<p>Edition: <span><%= @product.edition %></span></p>
							<p>Pages: <span><%= @product.pages %></span></p>
						</div>
						<div class="pro-inner-content pic-subject">
							<h3 class="productView-heading" id="related_sub">Related Subjects</h3>
							<ul>
								<% @product.tags.each do |tag| %>
									<li><a href="#"><%= tag.name%></a></li>
								<% end %>
							</ul>
						</div>
						<div class="pro-inner-content pic-review">
						<% if current_user.present? && !@review.present? %>
							<h3 class="productView-heading">Reviews</h3><a class="add-new-review">Review this book</a>
							<div class="new-review hidden">
								<%= form_for Review.new, remote: true, method: :post, html: {class: "form-inline studentMember-form dashboard-form"}, :url => "/reviews?id=#{@product.id}" do |f| %>
									<div id="rating"></div>
									<div class="form-group">
										<%= f.text_area :body, placeholder: "Please enter your review about rhis book", :class => 'form-control sm-form-fields' %>
									</div>
									<div class="form-group group-form-btn">
										<button type="button" class="cancel-new-review-btn blue-btn user-dashboard-btn">Cancel</button>
										<%= f.submit 'Save', :class => 'blue-btn user-dashboard-btn' %>
									</div>
								<% end %>
							</div>
						<% else %>
							<h3 class="productView-heading" id="reviews">Reviews</h3>
						<% end %>
							<% @product.reviews.each do |review| %>
								<div class="product-reviews">
									<% if review.user == current_user %>
										<label><%= review.user.first_name %> <%= review.user.last_name %> </label>
										<a ><i class="fa fa-pencil edit-user-review" aria-hidden="true"></i></a>
										<a href="<%= review_path(review) %>" data-method='delete'><i class="fa fa-trash delete-user-review" aria-hidden="true"></i></a>
										<div id="show-rating" ></div>
										<p class="user-review"><%= review.body %></p>
										<div class="edit-review hidden">
											<%= form_for :review, remote: true, method: :put, html: {class: "form-inline studentMember-form dashboard-form"}, :url => review_path(review.id) do |f| %>
												<div id="update-rating" ></div>
												<div class="form-group">
													<%= f.text_area :body, value: review.body, :class => 'form-control sm-form-fields' %>
												</div>
												<div class="form-group group-form-btn">
													<button type="button" class="cancel-btn blue-btn user-dashboard-btn">Cancel</button>
													<%= f.submit 'Update', :class => 'blue-btn user-dashboard-btn' %>
												</div>
											<% end %>
										</div>
									<% else %>
										<label><%= review.user.first_name %> <%= review.user.last_name %></label>
										<div id="users-rating-<%=review.id%>"></div>
										<p><%= review.body %></p>
									<% end %>
								</div>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- /.pro-overview-block -->
</div>

<!-- add to list modal -->
<div class="modal sm-modal dashBoard-list-modal addToList-Modal fade" id="addToListModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content sm-overlay-detail">
      <div class="modal-header sm-overlay-head">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add Product To List</h4>
      </div>
      <div class="modal-body sm-overlay-body">
	      <% if current_user.present? && current_user.wish_lists.present? %>
	      	<%= form_for :wish_list, remote: true, method: :put, html: {class: "studentMember-form dashboard-form dashboard-profile-form"}, :url => add_to_wish_list_path do |f| %>
	      		<%= f.hidden_field :product_id, :value => @product.id %>
		      		<div class="row">
			      			<% current_user.wish_lists.each do |list| %>
										<div class="col-md-4 col-sm-4">
											<div class="form-group">
												<div class="checkbox">
													<%= check_box_tag("wish_list[list_ids][]", list.id) %>
													<label><%= list.name %></label>
												</div>
											</div>
										</div>
						    <% end %>
							</div>
		        <%= f.submit 'Save', class: 'btn btn-primary sm-account-btn' %>
	        <% end %>
	      <% else %>
	      	<p>You dont have any list available. Please create a list.</p>
				<% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('.edit-user-review').click(function(){
			$('.user-review').addClass("hidden");
			$('#show-rating').addClass("hidden");
			$('.edit-review').removeClass("hidden");
		});

		$(".cancel-btn" ).click(function() {
			$('.user-review').removeClass("hidden");
			$('#show-rating').removeClass("hidden");
			$('.edit-review').addClass("hidden");
		});

		$('.add-new-review').click(function(){
			$('.add-new-review').addClass("hidden");
			$('.new-review').removeClass("hidden");
		});

		$(".cancel-new-review-btn" ).click(function() {
			$('.add-new-review').removeClass("hidden");
			$('.new-review').addClass("hidden");
		});

		$('#rating').raty({
			starOff : '../assets/star-off.png',
			starOn  : '../assets/star-on.png'
		});

		<% @all_reviews.each do |review|%>
			$('#users-rating-<%= review.id %>').raty({
				readOnly: true,
				score: '<%= review.rating.to_i %>',
				starOff : '../assets/star-off.png',
				starOn  : '../assets/star-on.png'
			});
		<% end %>

		$('#total-rating').raty({
			readOnly: true,
			half: true,
			score: '<%= @rating %>',
			starHalf : '../assets/star-half.png',
			starOff : '../assets/star-off.png',
			starOn  : '../assets/star-on.png'
		});

		<% if current_user.present? %>
			<% rate = Review.where(user_id: current_user.id, product_id: @product.id).first %>
			<% if rate.present? %>
				$('#update-rating').raty({
					score: '<%= rate.rating.to_i %>',
					starOff : '../assets/star-off.png',
					starOn  : '../assets/star-on.png'
				});

				$('#show-rating').raty({
					readOnly: true,
					score: '<%= rate.rating.to_i %>',
					starOff : '../assets/star-off.png',
					starOn  : '../assets/star-on.png'
				});
			<% end %>
		<% end %>
	});
</script>

<!-- <script>
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); 
  js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=239758226443634";
  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));
</script> -->