config/routes.rb
Rails.application.routes.draw do

  get 'blogs/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { registrations: 'registrations', sessions: 'sessions' }
  root 'home#index'

  get 'users/edit_profile', to: 'users#edit_profile', as: :user_edit_profile
  get 'users/show/profile', to: 'users#show_profile', as: :user_profile
  put 'add_to_wish_list', to: 'users#add_to_wish_list', as: :add_to_wish_list
  get 'user/dashboard', to: 'users#user_dashboard', as: :user_dashboard
  get 'user/new_address', to: 'users#new_address', as: :new_address
  get 'user/address_book', to: 'users#address_book', as: :address_book
  get 'student_club', to: 'users#student_club', as: :student_club
  get 'user_lists', to: 'users#user_lists', as: :user_lists
  post 'user/lists', to: 'users#create_list', as: :create_list
  get 'user/:id/lists', to: 'users#edit_list', as: :edit_list
  delete 'remove/list/product/:id', to: 'users#remove_from_list', as: :remove_from_list
  get 'my/orders', to: 'users#show_orders', as: :show_orders
  get 'order/:id', to: 'users#order_details', as: :order_details
  post 'user/new/address', to: 'users#add_new_address', as: :add_new_address
  get 'edit/:id/address', to: 'users#edit_address', as: :edit_address
  patch 'edit/:id/address', to: 'users#update_address', as: :update_address
  delete 'remove/address/:id', to: 'users#destroy_address', as: :destroy_address
  put '/set/default_address', to: 'users#set_default_address'
  get 'edit/:id/student_profile', to: 'users#edit_student_club', as: :edit_student_club
  put 'edit/:id/student_profile', to: 'users#update_student_club', as: :update_student_club
  get 'reviews', to: 'users#show_reviews', as: :reviews
  
  resources :products , only:[:index, :show]
  resources :blogs, only:[:index, :show]

  get 'terms_and_conditions', to: "requests#terms_and_conditions"
  get 'privacy_policy', to: "requests#privacy_policy"
  get "new_book_request", to: "requests#book_request_new"
  post 'book_requests', to: "requests#book_request_create"
  get "study_abroad", to: "requests#study_abroad_new"
  post 'study_abroads', to: "requests#study_abroad_create"
  get 'publish_request', to: 'requests#publish_requests_new'
  post 'publish_requests', to: 'requests#publish_requests_create'
  get 'bulk_order_info', to: 'requests#bulk_order_info'
  get 'new/student/membership', to: 'requests#new_student_membership_request', as: :new_student_membership
  post 'student/membership/step/one', to: 'requests#student_membership_step_one_create', as: :student_membership_step_one
  put 'student/membership/update', to: 'requests#student_membership_update', as: :student_membership_update
  get 'advertise', to: 'requests#advertise'
  post 'advertise_enquiry_create', to: 'requests#advertise_enquiry_create'

  resources :requests, :path => '', only:[:none] do 
    collection do
      get 'aboutus', to: 'faqs/aboutus_faqs'
      get 'bulk_order_faqs', to: 'faqs/bulkOrder_faqs'
      get 'publish_faqs', to: 'faqs/publish_faqs'
      get 'student_membership_faqs', to: 'faqs/student_membership_faqs'
      get 'forget_password_faqs', to: 'faqs/forget_password_faqs'
      get 'publisher_author_guidelines_faqs', to: 'faqs/publisher_author_guidelines_faqs'
      get 'shipping_delivary_faqs', to: 'faqs/shipping_delivary_faqs'
      get 'request_book_faqs', to: 'faqs/request_book_faqs'
      get 'shipping_rates_faqs', to: 'faqs/shipping_rates_faqs'
      get 'careers', to: 'requests#careers'
      get 'contact_us', to: 'requests#contact_us'
      post 'contact_us', to: 'requests#create_new_contact_request'
      get 'bulk_order_discounts', to: 'requests#bulk_order_discounts'
      post 'create_bulk_order_discount', to: 'requests#create_bulk_order_discount'
    end
  end

  resources :carts, only:[:none] do
    member do 
      put 'add_to_cart'
      put 'increase_quantity'
      put 'decrease_quantity'
      put 'decrease_quantity_cart'
      put 'increase_quantity_cart'
    end

    collection do 
      get 'show', as: :cart
    end 
  end

  resources :orders, only: [:create]
  get 'check_out', to: 'orders#check_out', as: :check_out

  resources :reviews, only:[:update, :destroy, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<!-- /.footer -->
<footer class="footer">
	<div class="footer-top">
		<div class="container">
			<div class="ft-inner-gradient">
				<div class="row">
					<div class="col-md-3 col-sm-3 col-xs-12">
						<div class="ft-container">
							<div class="ft-img">
								<%= image_tag("ft-1.png", alt: "IMG")%>
							</div>
							<div class="ft-detail">
								<label class="footer-label">REQUEST A BOOK</label>
								<p>CAN'T FIND A BOOK? LET US DO THE SEARCHING</p>
								<a href="<%= new_book_request_path %>">FIND NOW ></a>
							</div>
						</div>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<div class="ft-container">
							<div class="ft-img">
								<%= image_tag("ft-2.png", alt: "IMG")%>
							</div>
							<div class="ft-detail">
								<label class="footer-label">STUDY ABROAD</label>
								<p>A WHOLE WORLD OF OPPORTUNITIES AWAITS YOU</p>
								<a href="<%= study_abroad_path %>">Apply NOW ></a>
							</div>
						</div>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<div class="ft-container">
							<div class="ft-img">
								<%= image_tag("ft-3.png", alt: "IMG")%>
							</div>
							<div class="ft-detail">
								<label class="footer-label">DROPPINGO PRESS</label>
								<p>WOULD YOU LIKE TO AUTHOR A BOOK? BRING YOUR BOOK TO LIFE</p>
								<a href="<%= publish_request_path %>">learn MORE ></a>
							</div>
						</div>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<div class="ft-container">
							<div class="ft-img">
								<%= image_tag("ft-4.png", alt: "IMG")%>
							</div>
							<div class="ft-detail">
								<label class="footer-label">DROPPINGO Membership</label>
								<p>DON'T MISS OUT ON EXCLUSIVE DISCOUNTS & SAVINGS</p>
								<% if current_user.present? && current_user.student_profile.present? %>
									<a href="<%= student_club_path %>">Sign up ></a>
								<% else %>
									<a href="<%= new_student_membership_path %>">Sign up ></a>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="footer-menu">
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-sm-3 col-xs-12">
					<div class="fm-detail">
						<label class="footer-label">DROPPINGO SERVICES</label>
						<ul class="footer-menu-link">
							<li><a href="<%= advertise_path(:main_view => true) %>">ADVERTISE</a></li>
							<li><a href="<%= study_abroad_path %>">STUDY ABROAD</a></li>
							<li><a href="<%= student_membership_faqs_requests_path %>">STUDENT DISCOUNT</a></li>
							<li><a href="<%= publish_request_path %>">PUBLISH WITH DROPPINGO</a></li>
							<li><a href="<%= new_book_request_path %>">REQUEST A BOOK</a></li>
							<li><a href="<%= bulk_order_discounts_requests_path %>">BULK ORDER DISCOUNTS</a></li>
							<li><a href="<%= new_student_membership_path %>">DROPPINGO MEMBERSHIP</a></li>
							<li><a href="<%= publisher_author_guidelines_faqs_requests_path %>">PUBLISHER & AUTHOR GUIDELINES</a></li>
						</ul>
					</div>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<div class="fm-detail">
						<label class="footer-label">SHIPPING & DELIVERY</label>
						<ul class="footer-menu-link">
							<li><a href="<%= shipping_delivary_faqs_requests_path %>">ABOUT FREE SHIPPING</a></li>
							<li><a href="<%= shipping_delivary_faqs_requests_path %>">ABOUT SHIPPING</a></li>
							<li><a href="<%= shipping_rates_faqs_requests_path %>">SHIPPING RATES</a></li>
						</ul>
						<label class="footer-label">CUSTOMER SERVICES</label>
						<ul class="footer-menu-link">
							<li><a href="<%= contact_us_requests_path %>">CONTACT US</a></li>
							<li><a href="<%= privacy_policy_path %>">PRIVACY & COOKIE POLICY</a></li>
							<li><a href="<%= terms_and_conditions_path %>">TERMS & CONDITIONS</a></li>
						</ul>
					</div>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<div class="fm-detail">
						<label class="footer-label">ABOUT US</label>
						<ul class="footer-menu-link">
							<li><a href="<%= aboutus_requests_path %>">ABOUT DROPPINGO</a></li>
							<li><a href="#">INVESTOR RELATIONS</a></li>
							<li><a href="<%= careers_requests_path %>">CAREERS</a></li>
							<li><a href="<%= bulk_order_faqs_requests_path %>">FAQS</a></li>
						</ul>
					</div>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<div class="fm-detail">
						<label class="footer-label">CONNECT WITH US</label>
						<ul class="footer-socialIcons">
							<li><a href="<%= SocialShare.first.fb_link %>" class="footer-facebook"><span class="facebook-color"><i class="fa fa-facebook-official" aria-hidden="true"></i></span>FACEBOOK</a></li>
							<li><a href="<%= SocialShare.first.twitter_link %>" class="footer-twitter"><span class="twitter-color"><i class="fa fa-twitter" aria-hidden="true"></i></span>TWITTER</a></li>
							<li><a href="<%= SocialShare.first.pinterest_link %>" class="footer-pin"><span class="pinterest-color"><i class="fa fa-pinterest" aria-hidden="true"></i></span>PINTEREST</a></li>
							<li><a href="<%= SocialShare.first.instagram_link %>" class="footer-insta"><span class="instagram-color"><%=image_tag('insta-img.png', alt: "IMG", width: 19)%></span>INSTAGRAM</a></li>
							<li><a href="<%= SocialShare.first.youtube_link %>" class="footer-youtube"><span class="youtube-color"><%=image_tag('youtube-img.png', alt: "IMG", width: 18)%></span>YOUTUBE</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="footer-clients">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<ul>
						<li><%= image_tag("footer-1.png", alt: "IMG")%></li>
						<li><%= image_tag("footer-2.png", alt: "IMG")%></li>
						<li><%= image_tag("footer-3.png", alt: "IMG")%></li>
						<li><%= image_tag("footer-4.png", alt: "IMG")%></li>
						<li><%= image_tag("footer-5.png", alt: "IMG")%></li>
						<li><%= image_tag("footer-6.png", alt: "IMG")%></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</footer>
	<!-- /.footer -->

	<script type="text/javascript">
	$(document).ready(function(){ 
	  $('.flexslider').flexslider({
	    animation: "slide",
	    itemWidth: 230,
	    minItems: 2,
			maxItems: 5
	  });
	});
</script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-80654329-1', 'droppingo.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<header class="header">
	<div class="header-top">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-9 col-sm-9 col-xs-12">
					<ul class="ht-menu-list">
						<li><a href="<%= root_path %>">Home</a></li>
						<li><a href="<%= aboutus_requests_path %>">About</a></li>
						<li><a href="<%= contact_us_requests_path %>">Contact</a></li>
						<li><a href="<%= blogs_path %>">Blog</a></li>
					</ul>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12 text-right">
					<p class="getFree-text">
						<span class="basket-text">Spend Rs. 1000.<br> Get Free Delivery</span>
						<span class="cart-span">
							<%= link_to image_tag("cart-img.png"), cart_carts_path %>
							<span class="notific-span"><%= @cart.products.count %></span>
						</span>
					</p>
				</div>
			</div>
		</div>
	</div>
	<div class="header-center">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-2 col-sm-2 col-xs-12">
					<div class="site-logo">
						<%= link_to image_tag("logo.png", :width => 120), "/" %>
					</div>
				</div>
				<div class="col-md-7 col-sm-7 col-xs-12">
					<div class="search-bar">
					<!-- 	<form class="pro-search-form">
					    <div class="ps-input-area">
							  <input type="text" class="form-control" placeholder="Search by title, author, or subject">
							  <span class="search-icon"><i class="fa fa-search" aria-hidden="true"></i></span>
							  <button class="btn btn-default ps-btn" type="button">Search <span><i class="fa fa-search" aria-hidden="true"></i></span></button>
							</div>
						</form> -->
						<form method="get" action="/products" class="pro-search-form" name="productSearchForm">
						  <div class="ps-input-area">
						    <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search by title, author or subject" %>
					    	<span class="search-icon"><i class="fa fa-search" aria-hidden="true"></i></span>
					    	<%= button_tag(type: 'submit', class: "btn btn-default ps-btn", id: 'validForm') do %>
									Search <span><i class="fa fa-search" aria-hidden="true"></i></span>
								<% end %>
						  </div>
						</form>
					</div>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<% if !current_user %>
						<div class="header-login-btns">
							<div class="dropdown loginform-dropdown">
								<a href="#" class="blue-btn" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">login <span><i class="fa fa-user" aria-hidden="true"></i></span>
								</a>
								<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
							    <li>
							    	<div class="loginform-blog">
							    		<div class="loginform-heading">
							    			<h4>Sign In or Create an Account</h4>
							    		</div>
							    		<%= form_for :user, remote: true, html: {class: "login-form"}, :url => user_session_path do |f| %>
							    			<div class="form-top">
							    				<div class="ft-left">
							    					<div class="login-errors">
		    				
		    										</div>
							    					<div class="form-group">
															<%= f.email_field :email, class: "form-control input-fields", placeholder: "Email"%>
														</div>
														<div class="form-group">
															<%= f.password_field :password, class: "form-control input-fields", placeholder: "Password" %>
														</div>
													</div>
													<div class="ft-right">
														<%= f.submit 'Sign In', :class => 'blue-btn form-btn' %>
													</div>
												</div>
											<% end %>
											<div class="form-bottom">
												<div class="forgotPassword-link">
						    					<a href="#" data-toggle="modal" data-target="#forgetPasswordModal">Forgot Password?</a>
						    				</div>
						    				<div class="separator-form">
						    					<span>or</span>
						    				</div>
						    				<button class="createAccount-btn" data-toggle="modal" data-target="#myModal">Create An Account</button>
							    		</div>
							    	</div>
							    </li>
							  </ul>
							 </div>
							<a href="#" class="blue-btn" data-toggle="modal" data-target="#myModal">Sign up <span><i class="fa fa-user" aria-hidden="true"></i></span></a>
						<% else %>
							<div class="header-login-btns header-logout-btn">
								<a href="<%= destroy_user_session_path %>" class="blue-btn hlb-logout-btn" data-method="delete">Log out <span><i class="fa fa-user" aria-hidden="true"></i></span></a>
								<a href="<%= user_profile_path %>" class="blue-btn hlb-logout-btn">Dashboard <span><i class="fa fa-user" aria-hidden="true"></i></span></a>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Modal -->
	<div class="modal fade signup-modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content loginform-blog">
	      <div class="modal-header loginform-heading">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 id="myModalLabel">Create An Account</h4>
	      </div>
	      <div class="modal-body">
	    		<%= form_for User.new, remote: true, html: {class: "login-form signup-form", name: "signUpForm"}, :url => user_registration_path, method: :post do |f| %>
	    			<div class="form-top">
	    				<div class="signup-form-descrip top-descrip">
		    				<p>Fill in the fields below to create a Droppingo.com Account.</p>
		    				<p>If you already have an account, please <a href="#">Sign In ></a></p>
		    			</div>
		    			<div class="errors">
		    				
		    			</div>
	    				<div class="row">
	    					<div class="col-md-6 col-sm-6 col-xs-12">
		    					<div class="form-group">
								    <%= f.text_field :first_name, class: "form-control input-fields", placeholder: "First Name"%>
								  </div>
								</div>
								<div class="col-md-6 col-sm-6 col-xs-12">
								  <div class="form-group">
								    <%= f.text_field :last_name, class: "form-control input-fields", placeholder: "Last Name"%>
								  </div>
								</div>
	    				</div>
	    				<div class="row">
	    					<div class="col-md-6 col-sm-6 col-xs-12">
		    					<div class="form-group">
								    <%= f.email_field :email, id: "email", class: "form-control input-fields", placeholder: "Email Address"%>
								  </div>
								</div>
								<div class="col-md-6 col-sm-6 col-xs-12">
								  <div class="form-group">
								    <%= f.email_field :email_confirmation, id: "confirm_email", class: "form-control input-fields", placeholder: "Re-Enter Email Address"%>
								    <span id='email-message'></span>
								  </div>
								</div>
	    				</div>
	    				<div class="row">
	    					<div class="col-md-6 col-sm-6 col-xs-12">
		    					<div class="form-group">
								    <%= f.password_field :password, id: "password", class: "form-control input-fields", placeholder: "Password" %>
								  </div>
								</div>
								<div class="col-md-6 col-sm-6 col-xs-12">
								  <div class="form-group">
								    <%= f.password_field :password_confirmation, id: "confirm_password", class: "form-control input-fields", placeholder: "Confirm Password" %>
								  	<span id='password-message'></span>
								  </div>
								</div>
	    				</div>
	    				<div class="row">
	    					<div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-12">
	    						<%= f.submit 'Create An Account', :class => 'blue-btn form-btn' %>
	    					</div>
	    				</div>
	    			</div>
	    			<div class="signup-form-descrip bottom-descrip">
	    				<p>By registering you confirm that you agree to the </p>
	    				<p>Droppingo.com <a href="#">terms & conditions</a></p>
	    			</div>
	    		<% end %>
	      </div>
	    </div>
	  </div>
	</div>
	<!-- Modal -->
	<div class="header-bottom">
		<nav class="navbar navbar-default">
		  <div class="container-fluid">
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		    </div>
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav navbar-menu dropdown">
		      	<li>
		      		<a href="<%= root_path %>"><i class="fa fa-home" aria-hidden="true"></i></a>
		      	</li>
		      	<% Category.where(parent_id: nil).order(:name).each do |root| %>
			        <li class="atb-list">
			        	<a href="#" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><%= root.name %><span><i class="fa fa-caret-right" aria-hidden="true"></i></span></a>
			        	<ul class="dropdown-menu header-sub-menu" aria-labelledby="dropdownMenu2">
							    <li>
							    	<div class="subMenu-container">
							    		<div class="subMenu-head">
							    			<ul>
							    				<li><a href="#"><%= root.name %></a></li>
							    				<li><a href="<%= products_path(:category_id => root.id) %>">Shop All </a></li>
							    			</ul>
							    		</div>
							    		<div class="scrollbar-submenu" id="style-3">
								    		<div class="subMenu-content">
							    				<%# if root.descendants.count > 10 && root.descendants.count < 80 %>
							    				<div class="newspaper">
							    					<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix">
							    						<% root.children.each do |child| %>
									    					<div class="box col3">
								    							<a href="<%= products_path(:category_id => child.id) %>"><label><%= child.name %></label></a>
								    							<ul>
								    								<% child.children.each do |sub_child|%>
								    									<li class="unit"><a href="<%= products_path(:category_id => sub_child.id) %>"><%= sub_child.name %></a></li> 
								    								<% end %>
								    							</ul>
									    					</div>
								    					<% end %>
								    				</div>
							    				</div>
							    				<div class="submenu-book-block">
							    					<div class="subMenu-detail gen-list-detail">
							    						<% if Product.product_of_month(root).present? %>
							    							<label>Book of the Month</label>
							    							<span class="buybook-span"><%= image_tag(Product.product_of_month(root).avatar.url, alt:"book-IMG")%></span>
							    							<label><%= Product.product_of_month(root).title %></label>
							    							<a href="<%= product_path(Product.product_of_month(root).id) %>" class="buybook-link">Buy Now</a>
							    						<% end %>
							    					</div>
							    				</div>
								    		</div>
								    	</div>
							    	</div>
							    </li>
						  	</ul>
			        </li>
			      <% end %>
		      </ul>
		      <ul class="nav navbar-nav navbar-right navbar-right-btn">
		        <li><a href="<%= new_book_request_path %>" class="blue-btn">Request a Book <span><i class="fa fa-pencil-square-o" aria-hidden="true"></i></span></a></li>
		        <li><a href="<%= study_abroad_path %>" class="red-btn">Study Abroad <span><i class="fa fa-plane" aria-hidden="true"></i></span></a></li>
		      </ul>
		    </div>
		  </div>
		</nav>
	</div>

	<!-- Forget Password Modal -->
	<div class="modal sm-modal dashBoard-list-modal forgotPass-modal fade" id="forgetPasswordModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content sm-overlay-detail">
	      <div class="modal-header sm-overlay-head">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="myModalLabel">FORGET PASSWORD</h4>
	      </div>
	      <div class="modal-body sm-overlay-body">
	      	<%= form_for :user, html: {class: "create-list-form studentMember-form dashboard-form"}, :url => user_password_path do |f| %>
	      		<div class="form-group">
			        <%= f.email_field :email, class: 'form-control sm-form-fields', placeholder: 'Email' %>
			      </div>
		        <%= f.submit 'Send Password Reset Instructions', class: 'btn blue-btn' %>
	        <% end %>
	      </div>
	    </div>
	  </div>
	</div>
</header>

<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script> -->
<script type="text/javascript">
	// var $container = $('#container');
 //  $container.imagesLoaded( function(){
 //    $container.masonry({
 //      itemSelector : '.item',
 //      columnWidth : 202
 //    });
 //  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Droppingo</title>
    <link rel='shortcut icon' href='assets/favicon.png' type='image/x-icon'/ >
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script
        type="text/javascript"
        async defer
        src="//assets.pinterest.com/js/pinit.js"
    ></script>
    
  </head>

  <body>
    <%= render :partial => "layouts/header" %>
    <%= render 'toastr_rails/flash' %>
    <%= yield %>
    <%= render :partial => "layouts/footer" %>
  </body>

  <script type="text/javascript">
    toastr.options = {
      "closeButton": false,
      "debug": false,
      "newestOnTop": false,
      "progressBar": false,
      "positionClass": "toast-top-right",
      "preventDuplicates": true,
      "onclick": null,
      "showDuration": "300",
      "hideDuration": "1000",
      "timeOut": "3000",
      "extendedTimeOut": "1000",
      "showEasing": "swing",
      "hideEasing": "linear",
      "showMethod": "fadeIn",
      "hideMethod": "fadeOut"
    }

    $(document).ready(function() {
      $('.overlay-message').click(function() {
        $('.overlay-message').toggle("slide");
      });
    });

  </script>

  



</html>